name: CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  Tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: swift test